apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-mnpi
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0024-tenant/tkrw-pr712-0075-0024-app/devfile-sample-mnpi@sha256:e408c944720e93c10201990d86a565eb077f00f2f763b2540bdbd5e61379da4d
        name: my-nodejs
        resources: {}
status: {}
